### ISSUE TITLE
Handle /connect 1

### ISSUE THREAD

**Issue by din-din** [LastExceed/Exceed#37]
using /connect 1 results in a client freeze
figure out what exactly happens
(I have no freaking clue)

**Comment by LastExceed** [comment]
The client tries to build up a new connection to the (obviously invalid) ip "1" but keeps the current connection open until he receives a response from that ip (which obviously never happens). since the game freezes while waiting for a connection request to be accepted, the client stops sending packets in the meantime. only way to break out of this seems to be the current server killing the connection (eg if interprets the lack of packets as a timeout).

Players use this to quickly enter the main menu since this triggers a bug where the menu doesnt load a new world and puts your next selected character to the position of your last played character.

since we ripped out the loading screens from the game this technique has become obsolete and should be avoided.
