### ISSUE TITLE
bridge doesnt recognize game being closed

### ISSUE THREAD

**Issue by LastExceed** [LastExceed/Exceed#69]
after restarting the game fog remover ect dont work anymore

**Comment by NoEpicLoot** [comment]
As a player I want to be able to restart the game client without restarting the bridge, so that i can easily restart the game

When the game closes the bridge stays connected to killed process which is not existed anymore.
Bridge needs to check constantly if the process is still alive if not seek for a new one.


The task is done when I can close the game, keep the bridge open and reopen the game with the bridge fully functional.
