### ISSUE TITLE
logout on disconnect

### ISSUE THREAD

**Issue by LastExceed** [LastExceed/Exceed#75]
as a user I want the bridge to disconnect me when there is no connection anymore to the server so that I dont have to logout manually after the server crashed

right now after the server is shutdown the bridge stays connected to a non existing server which causes exceptions to be thrown which we dont handle.
The client is supposed to logout when the connection to the server drops.

the story is done when I can close the server and the bridge is not logged in any longer

**Comment by NoEpicLoot** [comment]
as a user I want the bridge to disconnect me when there is no connection anymore to the server so that I dont have to logout manually after the server crashed

right now after the server is shutdown the bridge stays connected to a non existing server which causes exceptions to be thrown which we dont handle.
The client is supposed to logout when the connection to the server drops.
